services:
    _defaults:
        public: true
        autowire: true

    PoPSchema\LocationPosts\ConditionalOnContext\AddLocationPostTypeToCustomPostUnionTypes\SchemaServices\ObjectTypeResolverPickers\LocationPostCustomPostObjectTypeResolverPicker:
        class: '\PoPSchema\LocationPostsWP\ConditionalOnContext\AddLocationPostTypeToCustomPostUnionTypes\Overrides\SchemaServices\ObjectTypeResolverPickers\LocationPostCustomPostObjectTypeResolverPicker'
