services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\LocationPosts\ConditionalOnContext\AddLocationPostTypeToCustomPostUnionTypes\SchemaServices\ObjectTypeResolverPickers\LocationPostCustomPostObjectTypeResolverPicker:
        class: '\PoPCMSSchema\LocationPostsWP\ConditionalOnContext\AddLocationPostTypeToCustomPostUnionTypes\Overrides\SchemaServices\ObjectTypeResolverPickers\LocationPostCustomPostObjectTypeResolverPicker'
